### ISSUE TITLE
Atributy

### ISSUE THREAD

**Issue by BulakM** [BulakM/RSP-skupina_6#1]
Mohl by někdo udělat seznam všech atributů dostupných pod jednotlivými entitami ?

**Comment by Vojta95** [comment]
klidně se na to kouknu, ale mám 2 dotazy - mám nechat hash přípěvku jako samostatný atribut, nebo ho mám dát jako klíč + jaký datový typ bude ten hash??

**Comment by BulakM** [comment]
Ano hash bude samostaný atribut. Pojmenuj ho, pokud mluvíš a atributu pro příspěvek, název. Hash jinak bude typu string

**Comment by Vojta95** [comment]
Je to nahraný, kdyby ti něco chybělo, tak se ozvi
