### ISSUE TITLE
Ikony

### ISSUE THREAD

**Issue by BulakM** [BulakM/RSP-skupina_6#2]
Mohl by jste někdo udělat ikony logos polytechnikos do mastepage a do záložky prohlížeče?

**Comment by Vojta95** [comment]
já se na to klidně kouknu....ale netuším, jak to logo vypadá 😂 
kde ho najdu? ve vydaných časopisech?

**Comment by BulakM** [comment]
Jo třeba vem to. A jako ikonu do záložky vezmi třeba tu z vspj

**Comment by Vojta95** [comment]
máš to hotový, poslal jsem ti to, tak to dej, kam potřebuješ

**Comment by Vojta95** [comment]
tady to máš, případně ti tu ikonu můžu poslat ve formátu *.ico


![ikona](https://user-images.githubusercontent.com/32438265/32693575-986a0c36-c72d-11e7-8eff-31ee7a89d9b0.png)
![logo](https://user-images.githubusercontent.com/32438265/32693576-989ce34a-c72d-11e7-8387-96a85ad715ac.png)
